CREATE TABLE IF NOT EXISTS Genre (
	id SERIAL PRIMARY KEY,
	title VARCHAR(60) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Singer (
	id SERIAL PRIMARY KEY,
	name VARCHAR(60) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS GenreSinger (
	genre_id INTEGER NOT NULL REFERENCES Genre(id),
	singer_id INTEGER NOT NULL REFERENCES Singer(id),
	CONSTRAINT PK PRIMARY KEY (genre_id, singer_id)
);

CREATE TABLE IF NOT EXISTS Album (
	id SERIAL PRIMARY KEY,
	title VARCHAR(60) NOT NULL UNIQUE,
	year_of_release INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS SingerAlbum (
	singer_id INTEGER REFERENCES Singer(id),
	album_id INTEGER REFERENCES Album(id),
	CONSTRAINT PK PRIMARY KEY (singer_id, album_id)
);

CREATE TABLE IF NOT EXISTS Collection (
	id SERIAL PRIMARY KEY,
	title VARCHAR(60) NOT NULL UNIQUE,
	year_of_release INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Track (
	id SERIAL PRIMARY KEY,
	album_id INTEGER NOT NULL UNIQUE REFERENCES Album(id),
	title VARCHAR(60) NOT NULL UNIQUE,
	duration INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS TrackCollection (
	track_id INTEGER NOT NULL REFERENCES Track(id),
	collection_id INTEGER NOT NULL REFERENCES Collection(id),
	CONSTRAINT PK PRIMARY KEY (collection_id, track_id)
);
	



CREATE TABLE IF NOT EXISTS Employee (
	id SERIAL PRIMARY KEY,
	name VARCHAR(30) NOT NULL,
	departament VARCHAR(60) NOT NULL,
	boss_id INTEGER NOT NULL REFERENCES Employee(id),
	departament_num INTEGER NOT NULL
);














